* Listener
DEFINE LISTENER(L1414) TRPTYPE(TCP) PORT(1414) CONTROL(QMGR) REPLACE
START LISTENER(L1414)

* App channel
DEFINE CHANNEL('DEV.APP.SVRCONN') CHLTYPE(SVRCONN) TRPTYPE(TCP) MCAUSER('app') REPLACE
ALTER QMGR CHLAUTH(DISABLED)

* ---- Cluster receiver for THIS QM (name must be unique and match senders on peers)
DEFINE CHANNEL('FNUNI.TO.{{SELF_QM}}') CHLTYPE(CLUSRCVR) TRPTYPE(TCP) +
  CONNAME('{{SELF_HOST}}(1414)') CLUSTER('FNUNI') REPLACE

* ---- Cluster senders to the two peers — names must match the CLUSRCVR on the peer
DEFINE CHANNEL('FNUNI.TO.{{PEER1_QM}}') CHLTYPE(CLUSSDR) TRPTYPE(TCP) +
  CONNAME('{{PEER1_HOST}}(1414)') CLUSTER('FNUNI') REPLACE
DEFINE CHANNEL('FNUNI.TO.{{PEER2_QM}}') CHLTYPE(CLUSSDR) TRPTYPE(TCP) +
  CONNAME('{{PEER2_HOST}}(1414)') CLUSTER('FNUNI') REPLACE

* Clustered queues
DEFINE QLOCAL('PAYMENT.REQUEST')  CLUSTER('FNUNI') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) REPLACE
DEFINE QLOCAL('PAYMENT.RESPONSE') CLUSTER('FNUNI') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) REPLACE

* DLQ
DEFINE QLOCAL('PAYMENT.DLQ') REPLACE
ALTER QMGR DEADQ('PAYMENT.DLQ')

* Workload
ALTER QMGR CLWLMRUC(999999999)
ALTER QMGR CLWLUSEQ(ANY)
