pong:
  server:
    port: 7000
  node-id: 1
  summary-interval-seconds: 60

# Netty configurations for better concurrency
server:
  reactive:
    max-threads: 500
    netty:
      boss-threads: 4
      worker-threads: 400

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: summary, health
