spring:
  application:
    name: pongservice

pong:
  server:
    port: 7000
    node-id: server1

server:
  reactive:
    max-threads: 200  # Controls the maximum number of Netty worker threads
    netty:
      boss-threads: 4     # Controls the number of threads for accepting connections
      worker-threads: 200 # Controls the number of threads for handling requests
