spring:
  application:
    name: pongserver

pong:
  server:
    port: 7000
    node-id: 1
  summary-interval-seconds: 60

management:
  server:
    port: 8000
  endpoints:
    web:
      exposure:
        include: health, summary

health:
  server:
    node-id: 1
