server:
  id: "pong-server-1"             # Unique identifier for the PongServer
  rsocketPort: 8080               # Port for the RSocket server listener
  webPort: 8082                   # Port for PongServer's health and summary endpoints

timeout:
  serverIdle: 60                  # Timeout for idle server connections in seconds

reporting:
  healthInterval: 60              # Interval for health reporting in seconds
  summaryInterval: 60             # Interval for summary metrics in seconds

netty:
  bossThreads: 1                  # Number of Netty boss threads
  workerThreads: 4                # Number of Netty worker threads
  serverBacklog: 128              # Backlog size for incoming connections

security:
  enableTls: false                # Whether to enable TLS for secure communication
  keyStorePath: ""                # Path to the TLS keystore (if TLS is enabled)
  keyStorePassword: ""            # Password for the TLS keystore (if TLS is enabled)
