pong:
  server:
    port: 8080       # Port where the RSocket server listens
    node-id: 1       # Unique node ID for the Pong server

netty:
  config:
    use-epoll: false # Use Epoll for Linux systems (set to true if supported)
    boss-threads: 1  # Number of Netty boss threads (handles incoming connections)
    worker-threads: 4 # Number of Netty worker threads (handles data processing)

reporting:
  interval:
    ms: 5000         # Reporting interval in milliseconds (default: 5 seconds)
