spring:
  application:
    name: pongserver
  server:
    port: 7000
    reactive:
      max-threads: 200     # Max threads for reactive server
      netty:
        boss-threads: 4    # Threads responsible for accepting new connections
        worker-threads: 200  # Threads responsible for processing requests

pong:
  server:
    node-id: 1  # Unique node ID for this server
  summary-interval-seconds: 60  # Interval to log the summary (in seconds)
