spring:
  application:
    name: pongserver

server:
  port: 8000            # Main application port
  reactive:
    max-threads: 500      # Maximum threads for the reactive server
    netty:
      boss-threads: 4     # Threads responsible for accepting new connections
      worker-threads: 400 # Threads responsible for processing requests

pong:
  server:
    port: 7000
    node-id: 1
  summary-interval-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: health, summary
logging:
  level:
    root: INFO
