spring:
  application:
    name: pongserver
  server:
    port: 7000
    reactive:
      max-threads: 200
      netty:
        boss-threads: 4
        worker-threads: 200
pong:
  server:
    node-id: 1  # Unique node ID for this server instance
  summary-interval-seconds: 60
