spring:
  application:
    name: pongserver
  server:
    port: 7000
    reactive:
      max-threads: 200
      netty:
        boss-threads: 4
        worker-threads: 200

pong:
  server:
    node-id: 1
  summary-interval-seconds: 60

health:
  server:
    port: 8000
    node-id: 1
