pong:
  server:
    port: 7000
  node-id: 1
  summary-interval-seconds: 60

# Netty configurations for high concurrency
server:
  reactive:
    max-threads: 500      # Maximum threads for the reactive server
    netty:
      boss-threads: 4     # Threads responsible for accepting new connections
      worker-threads: 400 # Threads responsible for processing requests

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: summary, health
