spring:
  application:
    name: pongserver

pong:
  server:
    port: 7000         # RSocket server port
    node-id: 1
  summary-interval-seconds: 60

health:
  server:
    port: 8000         # Health check endpoint port
    node-id: 1

server:
  port: ${pong.server.port}  # This is for the main RSocket server
