spring:
  application:
    name: pingclient

ping:
  server:
    host: localhost
    port: 7000
  client:
    node-id: 1
    threads: 5
    pings-per-second: 10
    payload-template: ping-node-$$\\{nodeId}-thread-$$\\{threadId}-count-$$\\{count}
    padding-size: 150  # Variable padding size
