spring:
  application:
    name: pingclient

server:
  port: 8082

ping:
  server:
    host: localhost
    port: 7000
  client:
    node-id: 1
    threads: 6
    pings-per-second: 300
    padding-size: 100
  summary-interval-seconds: 60
