spring:
  application:
    name: pingclient
ping:
  server:
    host: localhost
    port: 7000
  client:
    node-id: 1
    threads: 5
    pings-per-second: 10
    summary-interval-seconds: 60  # Change this value as needed (e.g., 1 for every second, 60 for every minute)
