spring:
  application:
    name: pingclient

ping:
  server:
    host: localhost   # Update this to your server IP if needed
    port: 7000
  client:
    node-id: 1
    threads: 6
    pings-per-second: 300
  summary-interval-seconds: 60

management:
  server:
    port: 8082            # Separate port for client summary endpoint
  endpoints:
    web:
      exposure:
        include: summary

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    reactor: DEBUG
