ping:
  nodeId: 1                      # Numeric Node ID for the Ping Client
  paddingSize: 1024              # Size of the padded payload in bytes
  ratePerSecond: 10              # Number of pings to send per second
  threadCount: 4                 # Number of threads for sending pings

connection:
  retryInterval: 5               # Initial retry interval in seconds
  maxRetryInterval: 30           # Maximum retry interval in seconds
  maxRetries: -1                 # Maximum retries (-1 for infinite retries)

rsocket:
  serverAddress: "localhost"     # Address of the PongServer
  serverPort: 8080               # Port of the PongServer (RSocket listener)

web:
  port: 8081                     # Port for PingClient's health and summary endpoints
