spring:
  application:
    name: pingclient

server:
  port: 8082            # Main application port
  reactive:
    max-threads: 500      # Maximum threads for the reactive server
    netty:
      boss-threads: 4     # Threads responsible for accepting new connections
      worker-threads: 400 # Threads responsible for processing requests

ping:
  server:
    host: localhost
    port: 7000
  client:
    node-id: 1
    threads: 6
    pings-per-second: 300
  summary-interval-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: summary
logging:
  level:
    root: INFO
