ping:
  server:
    host: localhost
    port: 7000
  client:
    node-id: 1
    threads: 6
    pings-per-second: 300
  summary-interval-seconds: 60

management:
  server:
    port: 8082 # Separate port for management endpoints
  endpoints:
    web:
      exposure:
        include: summary, health
