spring:
  application:
    name: pingclient
ping:
  server:
    host: localhost   # Update this to your server IP if needed
    port: 7000
  client:
    node-id: 1
    threads: 5
    pings-per-second: 10   # Number of pings sent per second per thread
    padding-size: 150      # Length of the padding message
    summary-interval-seconds: 60  # Interval to log the summary (in seconds)
