ping:
  client:
    node-id: 1                # Unique node ID for the Ping Client
    threads: 5                # Number of threads
    pings-per-second: 10      # Pings per second per thread
    payload-template: ping-node-{nodeId}-thread-{threadId}-count-{count}
    padding-size: 150         # Padding size for the payload
  server:
    host: localhost           # Pong Server host
    port: 7000                # Pong Server port

server:
  port: 8000                 # REST API port for the Ping Client

reporting:
  interval:
    ms: 5000                 # Interval for periodic reporting in milliseconds
