stages:
  - validate

validate_uploaded_file:
  stage: validate
  script:
    - echo "### Starting validation job ###"
    
    # Print the input variables passed from the Python script
    - echo "UPLOADED_FILE: $UPLOADED_FILE"
    - echo "CHECKSUM_FILE: $CHECKSUM_FILE"
    
    # Define the package registry URLs for the files
    - PACKAGE_URL="$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/package_name/version/$UPLOADED_FILE"
    - CHECKSUM_URL="$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/package_name/version/$CHECKSUM_FILE"
    
    # Fetch the uploaded .iris file
    - echo "Fetching uploaded file from GitLab Package Registry..."
    - curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --output downloaded_package.iris \
      "$PACKAGE_URL"
    
    # Fetch the checksum file (.cksum)
    - echo "Fetching checksum file from GitLab Package Registry..."
    - curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --output checksum_file.cksum \
      "$CHECKSUM_URL"
    
    # Extract expected checksum and filename from the .cksum file
    - EXPECTED_CHECKSUM=$(grep "Checksum" checksum_file.cksum | awk -F': ' '{ print $2 }')
    - EXPECTED_FILENAME=$(grep "File" checksum_file.cksum | awk -F': ' '{ print $2 }')
    - echo "Expected checksum: $EXPECTED_CHECKSUM"
    - echo "Expected filename: $EXPECTED_FILENAME"
    
    # Validate the filename
    - |
      if [ "$EXPECTED_FILENAME" != "$UPLOADED_FILE" ]; then
        echo "Filename mismatch! Expected: $EXPECTED_FILENAME, Found: $UPLOADED_FILE"
        exit 1
      fi
    
    # Perform checksum validation on the downloaded .iris file
    - CALCULATED_CHECKSUM=$(sha256sum downloaded_package.iris | awk '{ print $1 }')
    - echo "Calculated checksum: $CALCULATED_CHECKSUM"
    
    # Compare the calculated checksum with the expected checksum
    - |
      if [ "$CALCULATED_CHECKSUM" != "$EXPECTED_CHECKSUM" ]; then
        echo "Checksum mismatch! Expected: $EXPECTED_CHECKSUM, Found: $CALCULATED_CHECKSUM"
        exit 1
      fi
    
    - echo "Validation complete: File checksum and filename match."
  only:
    - main
