stages:
  - validate

validate_package:
  stage: validate
  script:
    - echo "### Starting validation of uploaded package ###"
    
    # Fetch the uploaded .iris file from the GitLab Package Registry
    - echo "Fetching uploaded file from GitLab Package Registry..."
    - curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --output downloaded_package.iris \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/package_name/version/$UPLOADED_FILE"
      
    # Fetch the checksum metadata file (.cksum) from the GitLab Package Registry
    - echo "Fetching checksum metadata file from GitLab Package Registry..."
    - curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --output downloaded_metadata.cksum \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/package_name/version/$CHECKSUM_FILE"

    # Validate the checksum and timestamp in the metadata against the uploaded file
    - echo "Validating the package checksum and timestamp against metadata..."
    
    # Calculate checksum of the downloaded .iris file
    - CHECKSUM=$(sha256sum downloaded_package.iris | awk '{ print $1 }')
    
    # Extract checksum and timestamp from the downloaded metadata file
    - METADATA_CHECKSUM=$(grep "Checksum" downloaded_metadata.cksum | awk -F': ' '{ print $2 }')
    - METADATA_TIMESTAMP=$(grep "Timestamp" downloaded_metadata.cksum | awk -F': ' '{ print $2 }')

    # Extract the timestamp of the uploaded file
    - TIMESTAMP=$(date -r downloaded_package.iris '+%Y-%m-%d %H:%M:%S')

    # Log checksum and timestamp information
    - echo "Checksum: $CHECKSUM"
    - echo "Metadata Checksum: $METADATA_CHECKSUM"
    - echo "Timestamp: $TIMESTAMP"
    - echo "Metadata Timestamp: $METADATA_TIMESTAMP"

    # Compare checksums
    - |
      if [ "$CHECKSUM" != "$METADATA_CHECKSUM" ]; then
        echo "Checksum mismatch! Expected: $METADATA_CHECKSUM, Found: $CHECKSUM"
        exit 1
      fi

    # Compare timestamps
    - |
      if [ "$TIMESTAMP" != "$METADATA_TIMESTAMP" ]; then
        echo "Timestamp mismatch! Expected: $METADATA_TIMESTAMP, Found: $TIMESTAMP"
        exit 1
      fi

    - echo "Validation passed successfully!"
    
  only:
    - main
