cert_duration_days: 365

ca_subject:
  C: "US"
  ST: "California"
  L: "San Francisco"
  O: "Vault Inc"
  CN: "Vault Root CA"
  emailAddress: "ca-admin@vault.local"

server_subject:
  C: "US"
  ST: "California"
  L: "San Francisco"
  O: "Vault Service"
  CN: "vault.service.local"
  emailAddress: "admin@vault.local"

subject_alt_names:
  - DNS:vault.service.local
  - DNS:localhost
  - IP:127.0.0.1
