* ----- Listener -----
* Docker containers start a listener on 1414 by default; no need to define (uncomment ONLY if running non-Docker native queue manager)
* DEFINE LISTENER(L1414)  TRPTYPE(TCP)  PORT(1414)  IPADDR(0.0.0.0)  CONTROL(QMGR) REPLACE
* START LISTENER(L1414)

* ----- TLS / Keystore (PKCS12) -----
ALTER QMGR SSLKEYR('/etc/certs/pki/qmgr/{{SELF_QM}}/qmgr.p12') +
  CERTLABL('qmgr-cert-{{SELF_QM}}')
ALTER QMGR KEYPWD('changeit')

* ----- Client (SVRCONN) channel with mTLS -----
DEFINE CHANNEL('DEV.APP.SVRCONN')  CHLTYPE(SVRCONN)  TRPTYPE(TCP) +
  SSLCIPH('TLS_AES_256_GCM_SHA384') +
  SSLCAUTH(REQUIRED)  REPLACE

* ----- CHLAUTH cert mapping -----
ALTER QMGR CHLAUTH(ENABLED)
SET CHLAUTH('DEV.APP.SVRCONN')  TYPE(SSLPEERMAP) +
  SSLPEER('CN=MQ-PRODUCER,OU=FN,O=FB,C=US') +
  USERSRC(MAP)  MCAUSER('MQ-PRODUCER')  ACTION(REPLACE)
SET CHLAUTH('DEV.APP.SVRCONN')  TYPE(SSLPEERMAP) +
  SSLPEER('CN=MQ-CONSUMER,OU=FN,O=FB,C=US') +
  USERSRC(MAP)  MCAUSER('MQ-CONSUMER')  ACTION(REPLACE)

* ----- Cluster receiver for THIS queue manager -----
DEFINE CHANNEL('FNUNI.TO.{{SELF_QM}}')  CHLTYPE(CLUSRCVR)  TRPTYPE(TCP) +
  CONNAME('{{SELF_HOST}}(1414)')  CLUSTER('FNUNI') +
  SSLCIPH('TLS_AES_256_GCM_SHA384') SSLCAUTH(REQUIRED) REPLACE

* ----- Cluster senders to seed QMs -----
DEFINE CHANNEL('FNUNI.TO.{{PEER1_QM}}')  CHLTYPE(CLUSSDR)  TRPTYPE(TCP) +
  CONNAME('{{PEER1_HOST}}(1414)')  CLUSTER('FNUNI') +
  SSLCIPH('TLS_AES_256_GCM_SHA384') SSLCAUTH(REQUIRED) REPLACE
DEFINE CHANNEL('FNUNI.TO.{{PEER2_QM}}')  CHLTYPE(CLUSSDR)  TRPTYPE(TCP) +
  CONNAME('{{PEER2_HOST}}(1414)')  CLUSTER('FNUNI') +
  SSLCIPH('TLS_AES_256_GCM_SHA384') SSLCAUTH(REQUIRED) REPLACE

* ----- Clustered queues -----
DEFINE QLOCAL('PAYMENT.REQUEST')   CLUSTER('FNUNI')  REPLACE
DEFINE QLOCAL('PAYMENT.RESPONSE')  CLUSTER('FNUNI')  REPLACE

* ----- Dead letter queue -----
DEFINE QLOCAL('PAYMENT.DLQ')  REPLACE
ALTER QMGR DEADQ('PAYMENT.DLQ')

* ----- OAM for MCAUSERs -----
SET AUTHREC PROFILE('PAYMENT.REQUEST')   OBJTYPE(QUEUE)  PRINCIPAL('MQ-PRODUCER')  AUTHADD(GET,INQ)
SET AUTHREC PROFILE('PAYMENT.RESPONSE')  OBJTYPE(QUEUE)  PRINCIPAL('MQ-PRODUCER')  AUTHADD(PUT,INQ)

SET AUTHREC PROFILE('PAYMENT.REQUEST')   OBJTYPE(QUEUE)  PRINCIPAL('MQ-CONSUMER')  AUTHADD(GET,INQ)
SET AUTHREC PROFILE('PAYMENT.RESPONSE')  OBJTYPE(QUEUE)  PRINCIPAL('MQ-CONSUMER')  AUTHADD(PUT,INQ)

* ----- Activate changes -----
REFRESH SECURITY TYPE(SSL)
REFRESH SECURITY TYPE(CONNAUTH)
REFRESH SECURITY TYPE(AUTHSERV)

* ----- FR/PR role appended by render script -----
